name: Sync to PizzaDAO Repo

on:
  push:
    branches:
      - main          # runs only when main is updated

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the code from this (CRXSS) repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Add PizzaDAO remote and push
      - name: Push to PizzaDAO repo
        env:
          TOKEN: ${{secrets.PIZZADAO_PUSH_TOKEN}}   # <-- secret must be named exactly
        run: |
          # Debug: show token length (masked, safe - just prints a number)
          echo "TOKEN-len=${#TOKEN}"

          # Git identity for the commit
          git config --global user.email "sync-bot@github.com"
          git config --global user.name  "Pizza Sync Bot"

          # Add remote using token
          git remote add pizzadao https://x-access-token:$TOKEN@github.com/PizzaDAO/Bitcoin-Pizza_Blastoff.git

          # Force-push main → main on PizzaDAO repo
          git push pizzadao main --force
